In [2]:
import torch

In [3]:
torch.__version__

'1.4.0'

In [1]:
import numpy as np

In [4]:
lst = [3,4,5,6]
arr = np.array(lst)

In [5]:
arr

array([3, 4, 5, 6])

In [6]:
arr.dtype

dtype('int32')

# Convert Numpy To Pytorch Torch

In [7]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [8]:
### Indexing similar to numpy
tensors[:2]

tensor([3, 4], dtype=torch.int32)

In [9]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

In [10]:
### Disadvantage of from_numpy. The array and tensor uses the same memory location
tensors[3]= 100

In [11]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [12]:
# If i will change anything to tensor it will change the numpy array also
arr

array([  3,   4,   5, 100])

In [13]:
### To prevent this type of change .we have other function torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [14]:
tensor_arr[3]= 20
print(tensor_arr)
print(arr)

tensor([ 3,  4,  5, 20], dtype=torch.int32)
[  3   4   5 100]


In [16]:
## zeros and Ones
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [17]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [23]:
# Two dimensional opeeration
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [24]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [28]:
a[:,0]

tensor([ 0,  3,  6,  9, 12], dtype=torch.int32)

In [29]:
a[0,:]

tensor([0, 1, 2], dtype=torch.int32)

In [38]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

In [37]:
a[1:3,:]

tensor([[3, 4, 5],
        [6, 7, 8]], dtype=torch.int32)

# Arithmetic Operations

In [41]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [42]:
a+b

tensor([ 7.,  9., 11.])

In [43]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [44]:
c=torch.zeros(3)
c

tensor([0., 0., 0.])

In [45]:
## Here we are storing the output in c variable
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [46]:
c

tensor([ 7.,  9., 11.])

In [47]:
## some more operations
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [48]:
torch.add(a,b).sum()

tensor(27.)

In [49]:
### dot products and multiplication operations

In [50]:
a = torch.tensor([3,4,5],dtype=torch.float)
b = torch.tensor([4,5,6],dtype=torch.float)

In [51]:
### Multiplication Opeartion
a.mul(b)

tensor([12., 20., 30.])

In [53]:
### 3*4+4*5+5*6
a.dot(b)

tensor(62.)

In [54]:
##### Matrix Multiplication

In [55]:
a = torch.tensor([[1,4,2],[1,5,5]],dtype=torch.float)## 2* 3 matrix
b = torch.tensor([[5,7],[8,6],[9,11]],dtype=torch.float)## 3*2 mattrix

In [56]:
a

tensor([[1., 4., 2.],
        [1., 5., 5.]])

In [57]:
b

tensor([[ 5.,  7.],
        [ 8.,  6.],
        [ 9., 11.]])

In [58]:
torch.matmul(a,b)## 2*2 mattrix

tensor([[55., 53.],
        [90., 92.]])

In [59]:
torch.mm(a,b)

tensor([[55., 53.],
        [90., 92.]])

In [60]:
a@b

tensor([[55., 53.],
        [90., 92.]])

In [ ]:
# matmul,mm and @@ all will perform the mattrix multiplication operation