In [1]:
import torch

In [2]:
x = torch.tensor(4.0,requires_grad=True)

In [3]:
x

tensor(4., requires_grad=True)

In [5]:
y = x**2

In [6]:
y

tensor(16., grad_fn=<PowBackward0>)

In [7]:
#### Back propagation for y= x^2 is y = 2x
y.backward()

In [9]:
## this is y = 2x
print(x.grad)

tensor(8.)


In [16]:
lst = [[2.,3.,1.],[4.,5.,3.],[7.,6.,4.]]

In [18]:
torch_input = torch.tensor(lst,requires_grad=True)

In [19]:
torch_input

tensor([[2., 3., 1.],
        [4., 5., 3.],
        [7., 6., 4.]], requires_grad=True)

In [20]:
## its basically y = x^3 + x^2 after derivative it becomes y = 3x^2 + 2x
y = torch_input**3 + torch_input**2

In [21]:
y

tensor([[ 12.,  36.,   2.],
        [ 80., 150.,  36.],
        [392., 252.,  80.]], grad_fn=<AddBackward0>)

In [24]:
print(torch_input.grad)

None


In [25]:
z = y.sum()

In [26]:
z

tensor(1040., grad_fn=<SumBackward0>)

In [28]:
z.backward()

In [29]:
torch_input.grad

tensor([[ 16.,  33.,   5.],
        [ 56.,  85.,  33.],
        [161., 120.,  56.]])